version: "3.9"

networks:
  application-network:
    driver: bridge

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: kayky0728/vite-react-tailwind:latest
    container_name: frontend
    tty: true
    volumes:
      - ./frontend/app:/usr/src/app
    ports:
      - 5173:5173
    networks:
      - application-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: kayky0728/java-springboot:latest
    container_name: backend
    tty: true
    volumes:
      - ./backend/app:/usr/src/app
    ports:
      - 4000:4000
    networks:
      - application-network
    depends_on:
      - database

  database:
    image: mysql/mysql-server:latest
    container_name: database
    restart: always
    environment:
      - MYSQL_DATABASE=applicationdb
      - MYSQL_ROOT_PASSWORD=senha123
    ports:
      - '3306:3306'
    volumes:
      - ./database/mysql/volume:/var/lib/mysql
    networks:
      - application-network

